### ISSUE TITLE
Usage of extracoders in Giraffe

### ISSUE THREAD

**Issue by kzbt** [thoth-org/Thoth.Json.Giraffe#11]
Hi, I'm new to fsharp and the ecosystem. I'm trying to get the following working with Satrun framework.

I want to have json responses that either have a payload or error like so:
```
{ "data": {...}}
{ "errors": [{"field_a": "field_a_error"}, {"field_b": "field_b_error"}]}
```
I modeled it as following with custom coders:

```fsharp
type ApiResponse<'t> =
  | ApiData of 't
  | ApiError of list<string * VError>

  static member Encoder =
    function
    | ApiData d ->
      let encoder = Encode.Auto.generateEncoderCached<'t>()
      Encode.object ["data", encoder(d)]
    | ApiError errors ->
      let encoder = Encode.Auto.generateEncoderCached<VError>()
      let jsonErrors = List.map (fun err -> Encode.object [(fst err), encoder (snd err)]) errors
      Encode.object ["errors", Encode.list jsonErrors]

  static member Decoder: Decoder<ApiResponse<'t>> =
    let dataDecoder =
      Decode.object (fun get ->
        Decode.Auto.generateDecoderCached<'t>()
        |> get.Required.Field "data"
        |> ApiData)

    let errorsListDecoder = Decode.Auto.generateDecoderCached<VError>() |> Decode.keyValuePairs
    let errorsDecoder =
      Decode.object (fun get ->
        errorsListDecoder
        |> get.Required.Field "errors"
        |> ApiError)

    Decode.oneOf [dataDecoder; errorsDecoder]
```
I used custom coders because the default serialization of union types wasn't very desirable to me.

I've added the custom coders as extra and added them to ThothSerializer like so:

```fsharp
let extraCoders =
  Extra.empty
  |> Extra.withCustom ApiResponse.Encoder ApiResponse.Decoder

let app =
    application {
        url ("http://0.0.0.0:" + port.ToString() + "/")
        use_router webApp
        memory_cache
        use_static publicPath
        use_json_serializer (Thoth.Json.Giraffe.ThothSerializer(SnakeCase, extraCoders))
        use_gzip
    }
```

However when I return an `ApiResponse<'t>` from an endpoint it is still using the default serialization.

```fsharp
let createProduct tenantId =
    fun next ctx -> task {
        let! productDto = Controller.getModel<Product.CreateDto> ctx
        match saveProduct productDto with
        | Success product ->
          let res = product |> ApiData
          return! json res next ctx
        | Failure errors ->
          let res = errors |> ApiError
          return! json res next ctx
    }
```

Did I miss something?

**Comment by MangelMaxime** [comment]
> I used custom coders because the default serialization of union types wasn't very desirable to me.

Hum, if you are using Thoth.Json.Net on the server and Thoth.Json on the client, the JSON representation should not be a problem. Because you don't work by reading the JSON but by using the type you get when decoding the JSON.

It is almost impossible to have a default JSON representation which suits everyone one.

And to answer, your original question no you didn't miss something. It is just that Thoth.Json doesn't allow you to customize the default representation of the known types when using Auto modules. So, for now, it is a limitation
