### ISSUE TITLE
Deserialize date type string as string

### ISSUE THREAD

**Issue by yang-qu** [thoth-org/Thoth.Json.Giraffe#31]
`Deserialize<'T>(json: string)` can deserialize date type string as string, but `Deserialize<'T>(bytes: byte[])` and `DeserializeAsync<'T>(stream: Stream)`  will fail because Newtonsoft.Json parse date type string as date type by default. 
e.g. 
> Error at: `$`
> Expecting a string but instead got: "2020-01-01T00:00:00Z"

Can we please add `jsonReader.DateParseHandling <- DateParseHandling.None` to both `Deserialize<'T>(bytes: byte[])` and `DeserializeAsync<'T>(stream: Stream)`? Because Deserialize<'T>(json: string) uses Decode.fromString, which already has `DateParseHandling.None` applied.

@MangelMaxime I am happy to submit a PR if you are OK with this fix.

**Comment by MangelMaxime** [comment]
Hello @yang-qu,

adding the missing `jsonReader.DateParseHandling <- DateParseHandling.None` is indeed a needed fix.

If you can please, send a PR with the required changes and if possible with tests to avoid regression in the future.

**Comment by yang-qu** [comment]
Created PR: https://github.com/thoth-org/Thoth.Json.Giraffe/pull/32

**Comment by MangelMaxime** [comment]
Thank you, I released a new version with your fix
