### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by MangelMaxime** [thoth-org/Thoth.Json.Giraffe#4]
It would be really nice to have some tests to check that Thoth.Json.Giraffe works.

The tests can be really basic at first:

1. Starting a Giraffe server
2. Execute a request to the server 
3. Check that the result is correct

**Comment by ericharding** [comment]
I'm interested in helping with this. Is there a particular test library you prefer?

**Comment by MangelMaxime** [comment]
Hello @ericharding, 
in general, I use [expecto](https://github.com/haf/expecto) in my tests.

If this library can work for this scenario I would be happy to keep it.

**Comment by rogerhmar** [comment]
Hi! I could help with tests (and CI?)

**Comment by MangelMaxime** [comment]
Hello @rogerhmar, thank you for volunteering.

Because @ericharding answered first I would say it depends on if he is still interested in it and can work on it in the near future. :) Just so you avoid working both on the same thing.

But definitly the goal, in the end, is to have the tests added and have a CI running with them. But I am not sure if someone else than me can configure the CI right now because I want to host it under the same org as other `thoth-org` project and I am the owner of it.

@ericharding If you are interested in working on it, please say it as a comment so I can assign you the issue :)

**Comment by ericharding** [comment]
I'm definitely still interested.  I'm also happy to work with @rogerhmar and split things up. I primarily jumped on this because I want to spend some time learning the ins-and outs of the thoth.json API so if you are interested in working on some CI integration that's definitely fine with me.

**Comment by MangelMaxime** [comment]
Ok, I let you decide together then :)

For the CI, I am using azrue-pipeline which is free for OSS projects. In other repos I have something like that: https://github.com/thoth-org/Thoth.Json/blob/master/azure-pipelines.yml

So the steps from my POV is to:

- Add the test project
- Update the build.fsx
- Check that it's working on azure-pipeline

**Comment by rogerhmar** [comment]
I can get started with setting up the test-project with Expecto and paket now.

**Comment by ericharding** [comment]
Works for me. Do you want to collaborate in a fork or branch?

**Comment by rogerhmar** [comment]
I have forked the repo and will add the branch 4_Add_tests. I will push it in a few minutes.

**Comment by rogerhmar** [comment]
I have forked the repo and started a branch. I have set up the test project. I have invited you both as collaborator (not sure if it makes sense to include you @MangelMaxime).

* I can start looking at the Fake scripts and build pipeline. 
* You can start making some tests, @ericharding (?)

**Comment by MangelMaxime** [comment]
Done by @MaxDeg in #8
