### ISSUE TITLE
Remove setStatusCode from ThothSerializer.RespondRawJson 

### ISSUE THREAD

**Issue by MaxDeg** [thoth-org/Thoth.Json.Giraffe#5]
Hello,

Would it be possible to remove the setStatusCode to 200 from ThothSerializer.RespondRawJson? Or create a new method which do not set the code?

In the case of api it's useful to return a json associated with a 400 or a 404.

**Comment by MangelMaxime** [comment]
Hello @MaxDeg yes, we can remove it,

would you be ok to send a PR?

We need to fix the comments and remove the `ctx.SetStatusCode 200` lines

**Comment by MaxDeg** [comment]
Sure I can do it :)
